"""Agregado correccion en algunas tablas

Revision ID: bc9c1e3c7622
Revises: 4acf638514ca
Create Date: 2026-01-29 18:07:24.552401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9c1e3c7622'
down_revision: Union[str, Sequence[str], None] = '4acf638514ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    transaction_type = sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', name='transactiontype')
    transaction_type.create(op.get_bind(), checkfirst=True)
    op.add_column('inventorymovement', sa.Column('transaction', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', name='transactiontype'), nullable=False))
    op.create_index(op.f('ix_inventorymovement_transaction'), 'inventorymovement', ['transaction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventorymovement_transaction'), table_name='inventorymovement')
    op.drop_column('inventorymovement', 'transaction')
    # ### end Alembic commands ###
